#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require(__DIR__ . '/vendor/autoload.php');
require(__DIR__ . '/vendor/yiisoft/yii2/Yii.php');
require(__DIR__ . '/common/config/bootstrap.php');
require(__DIR__ . '/console/config/bootstrap.php');

$config = yii\helpers\ArrayHelper::merge(
    require(__DIR__ . '/common/config/main.php'),
    require(__DIR__ . '/common/config/main-local.php'),
    require(__DIR__ . '/console/config/main.php'),
    require(__DIR__ . '/console/config/main-local.php')
);

if (!YII_ENV_TEST && extension_loaded('xhprof')) {
    xhprof_enable(XHPROF_FLAGS_CPU + XHPROF_FLAGS_MEMORY);
}

$application = new yii\console\Application($config);
$exitCode = $application->run();

if (!YII_ENV_TEST && extension_loaded('xhprof')) {
    $xhprofData  = xhprof_disable();

    include_once __DIR__ . "/../xhprof/xhprof_lib/utils/xhprof_lib.php";
    include_once __DIR__ . "/../xhprof/xhprof_lib/utils/xhprof_runs.php";

    $xhprof_runs = new XHProfRuns_Default();

    $xhprofUri = [];
    
    if (false === empty($argc)) {
        $xhprofUri = $argc;
    }

    $xhprofKey = str_replace(
        ['/', '.', '?', '&', ':'], //
        ['_', '-', '~', ';', '@'], //
        "yii-app-console" . ($xhprofUri ? '_' . urldecode(implode('__', $xhprofUri)) : '')
    );

    $runId = $xhprofRuns->save_run($xhprofData, $xhprofKey);
}

exit($exitCode);
